services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Specify the Dockerfile (default is Dockerfile)
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Specify the Dockerfile (default is Dockerfile)
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

volumes:
  postgres_data:
